Load apr-r575232 into vendor/apr/current.
git-svn-id: file:///srv/svn/limespot/vendor/apr/current@4652 a44d2f8d-3a13-463e-8d7a-201e96ec981d

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -12,14 +12,15 @@ VPATH = @srcdir@
 
 STDTEST_PORTABLE = \
 	testlockperf@EXEEXT@ \
-	testshmproducer@EXEEXT@ \
-	testshmconsumer@EXEEXT@ \
 	testmutexscope@EXEEXT@ \
 	testall@EXEEXT@
 
-OTHER_PROGRAMS = sendfile@EXEEXT@ \
-                 echod@EXEEXT@ \
-                 sockperf@EXEEXT@
+OTHER_PROGRAMS = \
+        sendfile@EXEEXT@ \
+	testshmproducer@EXEEXT@ \
+	testshmconsumer@EXEEXT@ \
+        echod@EXEEXT@ \
+        sockperf@EXEEXT@
 
 PROGRAMS = $(STDTEST_PORTABLE) $(STDTEST_NONPORTABLE) $(OTHER_PROGRAMS)
 
@@ -44,13 +45,20 @@ INCLUDES=-I$(INCDIR) -I$(srcdir)/../include
 LINK_PROG = $(LIBTOOL) $(LTFLAGS) --mode=link $(LT_LDFLAGS) $(COMPILE) @LT_NO_INSTALL@ $(ALL_LDFLAGS) -o $@
 
 check: $(STDTEST_PORTABLE) $(STDTEST_NONPORTABLE)
+	teststatus=0; \
+	progfailed=""; \
 	for prog in $(STDTEST_PORTABLE) $(STDTEST_NONPORTABLE); do \
 		./$$prog; \
-		if test $$? = 255; then \
-			echo "$$prog failed"; \
-			break; \
+		status=$$?; \
+		if test $$status != 0; then \
+			teststatus=$$status; \
+			progfailed="$$progfailed $$prog"; \
 		fi; \
-	done
+	done; \
+	if test $$teststatus != 0; then \
+		echo "Programs failed:$$progfailed"; \
+	fi; \
+	exit $$teststatus
 
 occhild@EXEEXT@: occhild.lo $(LOCAL_LIBS)
 	$(LINK_PROG) occhild.lo $(LOCAL_LIBS) $(ALL_LIBS)
@@ -110,9 +118,9 @@ TESTS = testutil.lo testtime.lo teststr.lo testvsn.lo testipsub.lo \
 	testdso.lo testoc.lo testdup.lo testsockets.lo testproc.lo \
 	testpoll.lo testlock.lo testsockopt.lo testpipe.lo testthread.lo \
 	testhash.lo testargs.lo testnames.lo testuser.lo testpath.lo \
-	testenv.lo testprocmutex.lo testrand2.lo testfnmatch.lo \
-        testatomic.lo testflock.lo testshm.lo testsock.lo testglobalmutex.lo \
-        teststrnatcmp.lo testfilecopy.lo testtemp.lo testlfs.lo
+	testenv.lo testprocmutex.lo testfnmatch.lo testatomic.lo testflock.lo \
+	testshm.lo testsock.lo testglobalmutex.lo teststrnatcmp.lo testfilecopy.lo \
+	testtemp.lo testlfs.lo testcond.lo
 
 testall@EXEEXT@: $(TESTS) mod_test.la libmod_test.la occhild@EXEEXT@ \
 	 readchild@EXEEXT@ abts.lo proc_child@EXEEXT@ \
